#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("kpack") and is_any_profile_enabled([profiles.full]):

#@ def compute_package_values():
#@   values = {
#@     "ca_cert_data": "",
#@     "kp_default_repository": {}
#@   }
#@
#@   if data.values.buildpacks.kpack:
#@     values.update(struct.decode(data.values.buildpacks.kpack))
#@   end
#@
#@   #! Compute values for CA Certificates
#@   if data.values.platform.ca_cert_data:
#@     values["ca_cert_data"] = values["ca_cert_data"] + data.values.platform.ca_cert_data
#@   end
#@
#@   #! Compute values for OCI Registry server
#@   if data.values.platform.oci_registry.server and data.values.platform.oci_registry.repository:
#@     if not hasattr(data.values.buildpacks.kpack, "kp_default_repository") or not hasattr(data.values.buildpacks.kpack.kp_default_repository, "name") or not data.values.buildpacks.kpack.kp_default_repository.name:
#@       values["kp_default_repository"]["name"] = data.values.platform.oci_registry.server.rstrip("/") + "/" + data.values.platform.oci_registry.repository.rstrip("/") + "/buildpacks"
#@     end
#@   end
#@
#@   #! Compute values for OCI Registry secret
#@   if data.values.platform.oci_registry.secret.name and data.values.platform.oci_registry.secret.namespace:
#@     if not hasattr(data.values.buildpacks.kpack, "kp_default_repository") or not hasattr(data.values.buildpacks.kpack.kp_default_repository, "secret") or not hasattr(data.values.buildpacks.kpack.kp_default_repository.secret, "name") or not hasattr(data.values.buildpacks.kpack.kp_default_repository.secret, "namespace") or not data.values.buildpacks.kpack.kp_default_repository.secret.name or not data.values.buildpacks.kpack.kp_default_repository.secret.namespace:
#@       values["kp_default_repository"]["secret"] = {}
#@       values["kp_default_repository"]["secret"]["name"] = data.values.platform.oci_registry.secret.name
#@       values["kp_default_repository"]["secret"]["namespace"] = data.values.platform.oci_registry.secret.namespace
#@     end
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: kpack
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: kpack
    kapp.k14s.io/change-rule.workspace-provisioner: upsert after upserting workspace-provisioner
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: kpack.packages.kadras.io
    versionSelection:
      constraints: 0.11.2+kadras.1
      prereleases: {}
  values:
  - secretRef:
      name: kpack-values
---
apiVersion: v1
kind: Secret
metadata:
  name: kpack-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end
