#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("metrics-server") and is_any_profile_enabled([profiles.full, profiles.serving]):

#@ def compute_package_values():
#@   return data.values.metrics_server
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metrics-server
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: metrics-server
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: metrics-server.packages.kadras.io
    versionSelection:
      constraints: 0.6.4
      prereleases: {}
  values:
  - secretRef:
      name: metrics-server-values
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end
