#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("cert-manager-webhook-hetzner"):

#@ def compute_package_values():
#@   return data.values.cert_manager_webhook_hetzner
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager-webhook-hetzner
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: cert-manager-webhook-hetzner
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cert-manager-webhook-hetzner.packages.kadras.io
    versionSelection:
      constraints: 0.6.5+kadras.2
      prereleases: {}
  values:
    - secretRef:
        name: cert-manager-webhook-hetzner-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-webhook-hetzner-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end
